"""add cases table

Revision ID: cf787e87360c
Revises: 54e5829f5ddc
Create Date: 2026-09-22 19:08:26.002616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cf787e87360c'
down_revision: Union[str, None] = '54e5829f5ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=True),
    sa.Column('original_query', sa.Text(), nullable=False),
    sa.Column('review_result', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('feedback_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
